name: Branches CI
on:
  push:
    branches:
      - "*"
      - "!main"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # name: Setup
      # uses: ./.github/workflows/setup.yml

    # uses: ./.github/workflows/setup.yml
    # runs-on: ubuntu-latest
    # steps:

    #   - name: Setup
    #     uses: ./.github/workflows/setup.yml


