name: Branches CI
on:
  push:
    branches:
      - "*"
      - "!main"

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./setup.yml


