name: Deploy

on:
  push:
    branches:
      - main

concurrency: "only one deploy at a time"

jobs:
  deploy-api:
    name: Build and Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm turbo run build --filter='./apps/api'

      # - name: Deploy
      #   run: wrangler deploy --env=preview --var VERSION:$(git rev-parse --short HEAD)
      #   working-directory: apps/api
      #   env:
      #     CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
