name: CI

on:
  push:
    branches:
      - github-actions-update

concurrency: "only one deploy at a time"

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  changes:
    name: Detect files changes
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      db: ${{ steps.filter.outputs.db }}
      api: ${{ steps.filter.outputs.api }}
      web-app: ${{ steps.filter.outputs.web-app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            db:
              - 'packages/db/**'
            api:
              - 'apps/api/**'
            web-app:
              - 'apps/web-app/**'

  db:
    name: Run DB steps
    runs-on: ubuntu-latest
    needs: changes
    if: ${{needs.changes.outputs.db == 'true'}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install
        uses: ./.github/actions/install

      - name: Run lint and format checks
        run: cd apps/api && pnpm biome ci .

      - name: Build
        run: pnpm turbo run build --filter='./apps/api'

      # - name: Run migrations
      #   run: DATABASE_URL=$DATABASE_URL pnpm db:apply-changes

      - name: Deploy
        run: wrangler deploy --minify src/index.ts --compatibility-date 2024-03-12 --name "health" --var DATABASE_URL:$DATABASE_URL
        working-directory: apps/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}