name: CI

on:
  push:
    branches:
      - main

concurrency: "only one deploy at a time"

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy-api:
    name: Build and Deploy API
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm turbo run build --filter='./apps/api'

      - name: Run migrations
        run: DATABASE_URL=$DATABASE_URL pnpm db:apply-changes

      - name: Deploy
        run: wrangler deploy --minify src/index.ts --compatibility-date 2024-03-12 --name "health" --var DATABASE_URL:$DATABASE_URL
        working-directory: apps/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  deploy-app:
    name: Build and Deploy App
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install
        uses: ./.github/actions/install

      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build
        run: TURBO_TELEMETRY_DISABLED=1 NEXT_TELEMETRY_DISABLED=1 pnpm turbo run build --filter='./apps/web-app'
