name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  changes:
    name: Detect files changes
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      db: ${{ steps.filter.outputs.db }}
      api: ${{ steps.filter.outputs.api }}
      web-app: ${{ steps.filter.outputs.web-app }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3.0.2
        name: Running filter
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            db:
              - 'packages/db/**'
            api:
              - 'apps/api/**'
            web-app:
              - 'apps/web-app/**'

  db:
    name: Run DB steps
    runs-on: ubuntu-latest
    needs: changes
    if: ${{needs.changes.outputs.db == 'true'}}
    defaults:
      run:
        working-directory: packages/db
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Lint and format checks
        run: bun tooling:ci
      - name: Make migrations
        run: DATABASE_URL=$DATABASE_URL bun run db:create-migrations
      - name: Run migrations
        run: DATABASE_URL=$DATABASE_URL bun run db:migrate

  # TODO: wait for db if the db job was run
  api:
    name: Run API steps
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.api == 'true' }}
    defaults:
      run:
        working-directory: apps/api
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: |
          bun install
          bun i wrangler
      - name: Lint and format checks
        run: bun tooling:ci
      - name: Deploy
        run: wrangler deploy --minify src/index.ts --compatibility-date 2024-03-12 --name "health" --var DATABASE_URL:$DATABASE_URL
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  web-app:
    name: Run web app steps
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.web-app == 'true' }}
    defaults:
      run:
        working-directory: apps/web-app
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Lint and format checks
        run: bun tooling:ci
